### ISSUE TITLE
Error when running 

### ISSUE THREAD

**Issue by N73dp** [potakhov/slack-zabbix-bot#1]
Try to run  ./slack-zabbix-bot configuration.json
and get Invalid credentials,any help please?
so i fixed this?but have another problem, slack message have html code not image,any advice please?

**Comment by potakhov** [comment]
most likely it is unable to authenticate with Zabbix using credentials from the configuration file

**Comment by N73dp** [comment]
I get something like this
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Author" content="Zabbix SIA" />
		<title>zabbix.wh.ent: Zabbix</title>
		<link rel="icon" href="favicon.ico">
		<link rel="apple-touch-icon-precomposed" sizes="76x76" href="img/apple-touch-icon-76x76-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="120x120" href="img/apple-touch-icon-120x120-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="152x152" href="img/apple-touch-icon-152x152-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="180x180" href="img/apple-touch-icon-180x180-precomposed.png">
		<link rel="icon" sizes="192x192" href="img/touch-icon-192x192.png">
		<meta name="msapplication-TileImage" content="img/ms-tile-144x144.png">
		<meta name="msapplication-TileColor" content="#d40000">
		<meta name="msapplication-config" content="none"/>
<link rel="stylesheet" type="text/css" href="styles/blue-theme.css" />
<style type="text/css">.na-bg, .na-bg input[type="radio"]:checked + label { background-color: #97AAB3 }
.info-bg, .info-bg input[type="radio"]:checked + label { background-color: #7499FF }
.warning-bg, .warning-bg input[type="radio"]:checked + label { background-color: #FFC859 }
.average-bg, .average-bg input[type="radio"]:checked + label { background-color: #FFA059 }
.high-bg, .high-bg input[type="radio"]:checked + label { background-color: #E97659 }
.disaster-bg, .disaster-bg input[type="radio"]:checked + label { background-color: #E45959 }
</style><script>var PHP_TZ_OFFSET = 10800;</script><script src="js/browsers.js"></script>
<script src="jsLoader.php?ver=3.2.6&amp;lang=ru_RU&showGuiMessaging=1"></script>
</head>
<body>
<div class="msg-bad-global" id="msg-bad-global"></div>
<div class="article"><div class="server-name">zabbix.wh.ent</div><div class="signin-container"><div class="signin-logo"></div><form method="post" action="index.php" accept-charset="utf-8"><input type="hidden" id="request" name="request" value="http://192.168.2.24/zabbix/chart2.php?graphid=99&amp;width=500&amp;height=100&amp;period=3600&amp;stime=20200101000000"><ul><li><label for="name">Имя пользователя</label><input type="text" id="name" name="name" value="" maxlength="255" autofocus="autofocus"></li><li><label for="password">Пароль</label><input type="password" id="password" name="password" value="" maxlength="255"></li><li><label for="autologin"><input type="checkbox" id="autologin" name="autologin" value="1">Запомнить меня на 30 дней</label></li><li><button type="submit" id="enter" name="enter" value="Войти">Войти</button></li><li class="sign-in-txt">or <a href="zabbix.php?action=dashboard.view">sign in as guest</a></li></ul></form></div><div class="signin-links"><a target="_blank" class="grey link-alt" href="http://www.zabbix.com/documentation/3.2/">Помощь</a>&nbsp;&nbsp;•&nbsp;&nbsp;<a target="_blank" class="grey link-alt" href="http://www.zabbix.com/support.php">Поддержка</a></div></div><div class="footer">&copy; 2001&ndash;2017, <a class="grey link-alt" target="_blank" href="http://www.zabbix.com/">Zabbix SIA</a></div></body>

**Comment by potakhov** [comment]
Well it's definitely failed to authorize. Did you specify valid Zabbix credentials in config?

**Comment by N73dp** [comment]
Yes, i got html code in slack message,now try to change user & password

**Comment by N73dp** [comment]
Ok,error whas in authorize, change in zabbix to http auth and it works.Thx alot!
